# Generated by Django 4.0.1 on 2022-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id_artist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('biography', models.CharField(max_length=200)),
                ('date_birth', models.IntegerField()),
                ('date_death', models.IntegerField()),
            ],
            options={
                'db_table': 'artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id_style', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('date_start', models.IntegerField()),
                ('date_finish', models.IntegerField()),
            ],
            options={
                'db_table': 'styles',
                'managed': False,
            },
        ),
    ]
