# Generated by Django 4.0.1 on 2022-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugadaika', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id_painting', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'paintings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id_technique', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'techniques',
                'managed': False,
            },
        ),
    ]
